###
POST http://localhost/api/identity/user
Content-Type: application/json

{
    "name": "Admin",
    "password": "adminPassword"
}

###
POST http://localhost/api/identity/login
Content-Type: application/json

{
    "name": "Admin",
    "password": "adminPassword"
}

###
POST http://localhost/api/identity/search
Content-Type: application/json
Cookie: sessionId=79483aec-ccb4-4e12-b26e-4e5c09d0c0b7

{
    "name": "Ad"
}

###
GET http://localhost/api/identity/user/current
Cookie: sessionId=79483aec-ccb4-4e12-b26e-4e5c09d0c0b7

###
GET http://localhost/api/identity/user
Cookie: sessionId=79483aec-ccb4-4e12-b26e-4e5c09d0c0b7